import type { Metadata } from 'next'
import './globals.css'
import { ThemeProvider } from '@/components/providers/ThemeProvider'
import { nutino_sans } from '@/lib/fonts/fonts'
import TopBar from '@/components/TopBar'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${nutino_sans.className} min-h-screen bg-very_light_gray font-normal text-very_dark_blue dark:bg-very_dark_blue dark:text-white`}
            >
                <ThemeProvider>
                    <TopBar />
                    {children}
                </ThemeProvider>
            </body>
        </html>
    )
}
